# Generated by Django 1.11.8 on 2017-12-05 09:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("trips", "0001_initial"),
        ("trips", "0002_auto_20150207_0440"),
        ("trips", "0003_odometer_km"),
        ("trips", "0004_auto_20150207_0447"),
        ("trips", "0005_remove_car_license_plate"),
        ("trips", "0006_auto_20170307_0642"),
        ("trips", "0007_auto_20170321_2241"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("license_plate", models.CharField(max_length=10)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Odometer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.Car"
                    ),
                ),
                ("km", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("date", models.DateField()),
                ("destination", models.CharField(max_length=20)),
                ("reason", models.CharField(max_length=20)),
                ("distance", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.Car"
                    ),
                ),
            ],
            options={"abstract": False, "ordering": ["-date"],},
        ),
        migrations.RemoveField(model_name="car", name="license_plate",),
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
