# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20170307_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date']},
        ),
    ]
